<?php

declare(strict_types=1);

return [

    // Suggested levels, institutions and subjects for the education form fields.
    // Users may still type any value.

    'levels' => [
        0 => 'Honors',
        1 => 'Masters',
        2 => 'PhD',
        3 => 'Diploma',
        4 => 'Certificate',
    ],

    'institutions' => [
        0 => 'Khulna University',
        1 => 'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
        2 => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University',
        3 => 'Bangabandhu Sheikh Mujibur Rahman Digital University',
        4 => 'Bangabandhu Sheikh Mujibur Rahman Maritime University',
        5 => 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University',
        6 => 'Bangabandhu Sheikh Mujibur Rahman University, Kishoreganj',
        7 => 'Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University',
        8 => 'Bangladesh Agricultural University',
        9 => 'Bangladesh Open University',
        10 => 'Bangladesh University of Engineering and Technology (BUET)',
        11 => 'Bangladesh University of Professionals (BUP)',
        12 => 'Bangladesh University of Textiles',
        13 => 'Barishal University',
        14 => 'Begum Rokeya University, Rangpur',
        15 => 'Chittagong University of Engineering & Technology (CUET)',
        16 => 'Comilla University',
        17 => 'Dhaka University of Engineering & Technology (DUET)',
        18 => 'Gopalganj Science and Technology University',
        19 => 'Hajee Mohammad Danesh Science and Technology University',
        20 => 'Islamic Arabic University',
        21 => 'Islamic University, Kushtia',
        22 => 'Jagannath University',
        23 => 'Jahangirnagar University',
        24 => 'Jashore University of Science and Technology',
        25 => 'Jatiya Kabi Kazi Nazrul Islam University',
        26 => 'Khulna University of Engineering & Technology (KUET)',
        27 => 'Khulna Agricultural University',
        28 => 'Kurigram Agricultural University',
        29 => 'Military Institute of Science and Technology (MIST)',
        30 => 'National University',
        31 => 'Noakhali Science and Technology University',
        32 => 'Pabna University of Science and Technology',
        33 => 'Patuakhali Science and Technology University',
        34 => 'Rabindra University, Bangladesh',
        35 => 'Rajshahi University of Engineering & Technology (RUET)',
        36 => 'Shahjalal University of Science and Technology',
        37 => 'Sheikh Hasina University',
        38 => 'Sher-e-Bangla Agricultural University',
        39 => 'Sylhet Agricultural University',
        40 => 'Chittagong University',
        41 => 'Dhaka University',
        42 => 'Rajshahi University',
    ],

    'subjects' => [
        0 => 'Bangla',
        1 => 'Accounting',
        2 => 'Agronomy',
        3 => 'Agroforestry',
        4 => 'Anthropology',
        5 => 'Arabic',
        6 => 'Architecture',
        7 => 'Banking and Insurance',
        8 => 'Biochemistry',
        9 => 'Biomedical Engineering',
        10 => 'Biotechnology',
        11 => 'Botany',
        12 => 'Chemical Engineering',
        13 => 'Chemistry',
        14 => 'Civil Engineering',
        15 => 'Computer Science and Engineering',
        16 => 'Criminology',
        17 => 'Data Science',
        18 => 'Dentistry (BDS)',
        19 => 'Development Studies',
        20 => 'Drawing and Painting',
        21 => 'Economics',
        22 => 'Education',
        23 => 'Electrical and Electronic Engineering',
        24 => 'Electronics and Communication Engineering',
        25 => 'English',
        26 => 'Entomology',
        27 => 'Environmental Science',
        28 => 'Finance',
        29 => 'Fine Arts',
        30 => 'Fisheries',
        31 => 'Food Engineering',
        32 => 'Food Science and Technology',
        33 => 'Forensic Science',
        34 => 'Gender and Development Studies',
        35 => 'Genetic Engineering and Biotechnology',
        36 => 'Geography and Environment',
        37 => 'Geology',
        38 => 'Graphic Design',
        39 => 'History',
        40 => 'Horticulture',
        41 => 'Human Resource Management',
        42 => 'Industrial and Production Engineering',
        43 => 'Information Technology',
        44 => 'International Relations',
        45 => 'Islamic History and Culture',
        46 => 'Islamic Studies',
        47 => 'Law (LL.B)',
        48 => 'Linguistics',
        49 => 'Management',
        50 => 'Marketing',
        51 => 'Mass Communication and Journalism',
        52 => 'Materials Science and Engineering',
        53 => 'Mathematics',
        54 => 'Mechanical Engineering',
        55 => 'Mechatronics Engineering',
        56 => 'Medicine (MBBS)',
        57 => 'Microbiology',
        58 => 'Molecular Biology',
        59 => 'Music',
        60 => 'Naval Architecture and Marine Engineering',
        61 => 'Nursing',
        62 => 'Nutrition and Food Science',
        63 => 'Oceanography',
        64 => 'Peace and Conflict Studies',
        65 => 'Petroleum and Mining Engineering',
        66 => 'Pharmacy',
        67 => 'Philosophy',
        68 => 'Physical Education',
        69 => 'Physics',
        70 => 'Plant Pathology',
        71 => 'Political Science',
        72 => 'Population Sciences',
        73 => 'Psychology',
        74 => 'Public Administration',
        75 => 'Public Health',
        76 => 'Poultry Science',
        77 => 'Robotics and Mechatronics Engineering',
        78 => 'Sanskrit',
        79 => 'Sociology',
        80 => 'Software Engineering',
        81 => 'Soil Science',
        82 => 'Statistics',
        83 => 'Textile Engineering',
        84 => 'Theater and Performance Studies',
        85 => 'Tourism and Hospitality Management',
        86 => 'Urban and Regional Planning',
        87 => 'Women and Gender Studies',
        88 => 'Zoology',
    ],

];
